--------------------------------------------------------
--  File created - Monday-April-12-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table LOGINTABLE
--------------------------------------------------------

  CREATE TABLE "BUHARUV_ID"."LOGINTABLE" 
   (	"ID" NUMBER(*,0), 
	"USERNAME" VARCHAR2(150 BYTE), 
	"PASS" VARCHAR2(150 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into BUHARUV_ID.LOGINTABLE
SET DEFINE OFF;
Insert into BUHARUV_ID.LOGINTABLE (ID,USERNAME,PASS) values (1,'buharu','pass');
--------------------------------------------------------
--  DDL for Index SYS_C00242529
--------------------------------------------------------

  CREATE UNIQUE INDEX "BUHARUV_ID"."SYS_C00242529" ON "BUHARUV_ID"."LOGINTABLE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table LOGINTABLE
--------------------------------------------------------

  ALTER TABLE "BUHARUV_ID"."LOGINTABLE" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BUHARUV_ID"."LOGINTABLE" MODIFY ("PASS" NOT NULL ENABLE);
  ALTER TABLE "BUHARUV_ID"."LOGINTABLE" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "BUHARUV_ID"."LOGINTABLE" MODIFY ("ID" NOT NULL ENABLE);
